export const ACT_ADD_COMMENT = 'ACT_ADD_COMMENT';
export const ACT_GET_COMMENTS = 'ACT_GET_COMMENTS';
export const ACT_GET_COMMENTS_SUCCESS = 'ACT_GET_COMMENTS_SUCCESS';
export const ACT_GET_COMMENTS_ERROR = 'ACT_GET_COMMENTS_ERROR';
export const ACT_GET_POSTS = 'ACT_GET_POSTS';
export const ACT_GET_POSTS_SUCCESS = 'ACT_GET_POSTS_SUCCESS';
export const ACT_GET_POSTS_ERROR = 'ACT_GET_POSTS_ERROR';
export const ACT_CLEAN_POSTS = 'ACT_CLEAN_POSTS';